name:fabric Pipeline Test

on:
 push:
  branches:
   -main
   -test-pipeline-setup

jobs:
 check-fabric-files:
  runs-on: unbuntu-latest
  steps:
  -name: Checkout code
   uses:actions/checkout@v3

   -name: Print structure
   run: |
    echo "listing files in repo"
